# name: print used memory
# hosts: localhost
# tasks:
#   - name: get memory
#     ansible.builtin.shell: free | grep Mem
#     register: free  #this is the variable i'm declaring
#   - name: print free variable
#     ansible.builtin.debug:
#       msg: "{{free}}" #im declaring my variable here
#
#
#wanting to see only  the free.stdout part of the free | grep mem
#
# name: print used memory
# hosts: localhost
# tasks:
#   - name: get memory
#     ansible.builtin.shell: free | grep Mem
#     register: free  #this is the variable i'm declaring
#   - name: print free variable
#     ansible.builtin.debug:
#       msg: "{{free.stdout}}" #im declaring my variable here to see only the free.stdout
#
#
 - name: print used memory
   hosts: localhost
   tasks:
     - name: get memory
       ansible.builtin.shell: free | grep Mem | xargs
       register: free  #this is the variable i'm declaring

     - name: setting a fact  # this is declaring something to be something using the set_fact module
       ansible.builtin.set_fact:
         FREE: "{{ free.stdout | split(' ') }}" #splitting what i want to see

    
     - name: print free variable after setting a fact
       ansible.builtin.set_fact:
         total: "{{ FREE[1] }}"
         free: "{{ FREE[2] }}"



